### ISSUE TITLE
What is the `todo-by` annotation and what is it supposed to do?

### ISSUE THREAD

**Issue by janopae** [leighman/psalm-plugin-todo-by#3]
I can't find anything about a `@todo-by` DocBlock annotation on the Internet.

**Comment by leighman** [comment]
Nor can I...
I'm pretty sure it was inspired by a Ruby library.
Basically you can use `@todo-by 2024-01-22` and it will become an error after that instant.

**Comment by janopae** [comment]
Thanks!
